import type { Product } from "./cart-context";

// Original images
import productFlanellBlau from "@/assets/product-flanell-blau.jpg";
import productFlanellItal from "@/assets/product-flanell-ital.jpg";
import productSchurwolle from "@/assets/product-schurwolle.jpg";
import productFlanellGrau from "@/assets/product-flanell-grau.jpg";
import productFlanellPremium from "@/assets/product-flanell-premium.jpg";
import productPailletten from "@/assets/product-pailletten.jpg";
import productFlanellStretch from "@/assets/product-flanell-stretch.jpg";
import productMantelstoff from "@/assets/product-mantelstoff.jpg";

// New images from Weber
import productSchurwolleBlau from "@/assets/product-schurwolle-blau.jpg";
import productWalkstoffDesigner from "@/assets/product-walkstoff-designer.jpg";
import productWalkloden from "@/assets/product-walkloden.jpg";
import productFeinstrick1 from "@/assets/product-feinstrick-1.jpg";
import productFeinstrick2 from "@/assets/product-feinstrick-2.jpg";
import productMantelDesigner from "@/assets/product-mantel-designer.jpg";
import productJackenMantel from "@/assets/product-jacken-mantel.jpg";
import productWestfalenstoff from "@/assets/product-westfalenstoff.jpg";
import productLeinenDesigner from "@/assets/product-leinen-designer.jpg";
import productSchurwolleItal from "@/assets/product-schurwolle-ital.jpg";
import productElastikSamt from "@/assets/product-elastik-samt.jpg";
import productStickstoff from "@/assets/product-stickstoff.jpg";
import productLeinen from "@/assets/product-leinen.jpg";
import productFlanellBraun from "@/assets/product-flanell-braun.jpg";
import productFlanellDunkel from "@/assets/product-flanell-dunkel.jpg";
import productFlanellPremium2 from "@/assets/product-flanell-premium-2.jpg";

// Page 3: Homepage featured products
import productBoucleDesigner from "@/assets/product-boucle-designer.jpg";
import productJerseyDesigner from "@/assets/product-jersey-designer.jpg";
import productJerseyItal from "@/assets/product-jersey-ital.jpg";
import productBaumwolleDesigner from "@/assets/product-baumwolle-designer.jpg";
import productViskoseItal from "@/assets/product-viskose-ital.jpg";
import productLeinenViskose from "@/assets/product-leinen-viskose.jpg";
import productBoucleItal from "@/assets/product-boucle-ital.jpg";
import productJeansstoffDesigner from "@/assets/product-jeansstoff-designer.jpg";
import productSpitzeDesigner from "@/assets/product-spitze-designer.jpg";
import productBaumwolleItal from "@/assets/product-baumwolle-ital.jpg";

export interface ProductDetail {
  composition: string;
  width: string;
  weight: string;
  careInstructions: string[];
  description: string;
  sampleAvailable: boolean;
  samplePrice: number;
}

export const categories = [
  "Alle",
  "Flanell",
  "Schurwolle",
  "Designer",
  "Angebot",
  "Leinen",
  "Strickstoffe",
  "Walkstoffe",
  "Mantel & Jackenstoffe",
  "Baumwollstoffe",
  "Jersey",
  "Bouclé",
  "Spitzenstoffe",
  "Viskose",
] as const;

// Fabric type filters matching stoffverkauf-weber.de
export const fabricTypeFilters = [
  "Designerstoffe",
  "Italienische Stoffe",
  "Angebote",
  "Futterstoffe",
  "Italienische Seide",
  "Italienischer Jersey",
  "Italienisches Leinen",
  "Italienische Schurwolle",
  "Elegante-Stoffe",
  "Pailletten & Perlen",
  "Spitzenstoffe",
  "Jacquard-Stoffe",
  "Bouclé & Tweed",
  "Kleider & Blusenstoffe",
  "Strickstoffe",
  "Mantel & Jackenstoffe",
  "Pelzimitationen",
  "Cashmere",
  "Walkstoffe",
  "Wollfilz",
  "T-Shirtstoffe",
  "Stretchstoffe",
  "Baumwollstoffe",
  "Stickereistoffe",
  "Leder & Lederimitat",
  "Westfalenstoffe",
] as const;

export type FabricType = typeof fabricTypeFilters[number];

export const productDetails: Record<string, ProductDetail> = {
  "1": {
    composition: "80% Schurwolle, 20% Polyamid",
    width: "140 cm",
    weight: "320 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Hochwertiger Flanell aus italienischer Schurwolle in einem zeitlosen Mittelblau. Weicher Griff, ideal für Blazer, Anzüge und elegante Hosen.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "2": {
    composition: "100% Schurwolle",
    width: "140 cm",
    weight: "300 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Feiner italienischer Flanell in klassischer Qualität. Weich und geschmeidig, perfekt für hochwertige Herrenbekleidung und Damenmode.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "3": {
    composition: "90% Schurwolle, 10% Kaschmir",
    width: "140 cm",
    weight: "340 g/m²",
    careInstructions: ["Chemische Reinigung empfohlen", "Handwäsche möglich bei 30°C", "Bügeln Stufe 1-2", "Liegend trocknen"],
    description: "Luxuriöser Schurwoll-Flanell mit Kaschmiranteil für ein besonders weiches Griffgefühl. Italienische Herkunft garantiert höchste Qualität.",
    sampleAvailable: true,
    samplePrice: 3.00,
  },
  "4": {
    composition: "85% Schurwolle, 15% Polyamid",
    width: "140 cm",
    weight: "310 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Eleganter Flanell in einem vielseitigen Grau. Perfekt für Business-Garderobe und formelle Anlässe.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "5": {
    composition: "100% Merinowolle",
    width: "150 cm",
    weight: "360 g/m²",
    careInstructions: ["Nur chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2 mit Tuch", "Nicht im Trockner trocknen"],
    description: "Premium-Qualität aus feinster Merinowolle. Besonders weich und temperaturregulierend. Für anspruchsvolle Projekte.",
    sampleAvailable: true,
    samplePrice: 3.50,
  },
  "6": {
    composition: "60% Polyester, 30% Wolle, 10% Pailletten",
    width: "140 cm",
    weight: "280 g/m²",
    careInstructions: ["Handwäsche bei 30°C", "Nicht bleichen", "Nicht bügeln", "Nicht im Trockner trocknen"],
    description: "Auffälliger Walkstoff mit funkelnden Pailletten. Ideal für Abendmode, Kostüme und besondere Anlässe.",
    sampleAvailable: true,
    samplePrice: 2.00,
  },
  "7": {
    composition: "75% Schurwolle, 22% Polyamid, 3% Elasthan",
    width: "155 cm",
    weight: "290 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Flanell mit Stretchanteil für optimale Bewegungsfreiheit. Behält seine Form und bietet Komfort.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "8": {
    composition: "70% Wolle, 20% Polyamid, 10% Viskose",
    width: "150 cm",
    weight: "450 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Schwerer, hochwertiger Mantelstoff mit exzellenter Wärmeisolierung. Ideal für elegante Wintermäntel.",
    sampleAvailable: true,
    samplePrice: 3.00,
  },
  "9": {
    composition: "100% Schurwolle",
    width: "150 cm",
    weight: "280 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Feine italienische Schurwolle in elegantem Blauton. Leicht und geschmeidig, ideal für Anzüge und Kostüme.",
    sampleAvailable: true,
    samplePrice: 2.00,
  },
  "10": {
    composition: "80% Wolle, 20% Polyamid",
    width: "150 cm",
    weight: "400 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Designer-Walkstoff mit weichem Griff und edler Optik. Perfekt für Mäntel und hochwertige Jacken.",
    sampleAvailable: true,
    samplePrice: 3.00,
  },
  "11": {
    composition: "100% Wolle",
    width: "140 cm",
    weight: "420 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Traditioneller Walkloden in kräftiger Qualität. Wind- und wasserabweisend, perfekt für Outdoor-Kleidung.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "12": {
    composition: "70% Viskose, 30% Polyamid",
    width: "150 cm",
    weight: "220 g/m²",
    careInstructions: ["Maschinenwäsche 30°C", "Nicht bleichen", "Bügeln Stufe 1", "Nicht im Trockner trocknen"],
    description: "Italienischer Feinstrickstoff mit wunderbarem Fall. Leicht und angenehm auf der Haut.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "13": {
    composition: "65% Viskose, 35% Polyamid",
    width: "140 cm",
    weight: "210 g/m²",
    careInstructions: ["Maschinenwäsche 30°C", "Nicht bleichen", "Bügeln Stufe 1", "Nicht im Trockner trocknen"],
    description: "Weicher Feinstrickstoff aus Italien in gedecktem Farbton. Ideal für Kleider und Oberteile.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "14": {
    composition: "90% Wolle, 10% Kaschmir",
    width: "150 cm",
    weight: "480 g/m²",
    careInstructions: ["Nur chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2 mit Tuch", "Nicht im Trockner trocknen"],
    description: "Edler Designer-Mantelstoff in luxuriöser Schwere. Kaschmiranteil für besondere Weichheit und Eleganz.",
    sampleAvailable: true,
    samplePrice: 3.50,
  },
  "15": {
    composition: "85% Wolle, 15% Mohair",
    width: "150 cm",
    weight: "460 g/m²",
    careInstructions: ["Nur chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2 mit Tuch", "Nicht im Trockner trocknen"],
    description: "Hochwertiger Jacken- und Mantelstoff mit Mohairanteil. Wärmend, robust und mit schönem Glanz.",
    sampleAvailable: true,
    samplePrice: 3.50,
  },
  "16": {
    composition: "100% Baumwolle",
    width: "150 cm",
    weight: "140 g/m²",
    careInstructions: ["Maschinenwäsche 40°C", "Bleichen erlaubt", "Bügeln Stufe 3", "Trockner möglich"],
    description: "Hochwertiger Westfalenstoff aus reiner Baumwolle. Pflegeleicht und vielseitig einsetzbar für Patchwork und Deko.",
    sampleAvailable: true,
    samplePrice: 1.50,
  },
  "17": {
    composition: "100% Leinen",
    width: "150 cm",
    weight: "200 g/m²",
    careInstructions: ["Maschinenwäsche 40°C", "Nicht bleichen", "Bügeln Stufe 3", "Nicht im Trockner trocknen"],
    description: "Designer-Leinen aus Italien. Natürlich kühlend und atmungsaktiv, ideal für sommerliche Kleidungsstücke.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "18": {
    composition: "100% Schurwolle",
    width: "150 cm",
    weight: "330 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Italienische Schurwolle in klassischer Qualität. Vielseitig einsetzbar für Blazer, Röcke und Hosen.",
    sampleAvailable: true,
    samplePrice: 3.00,
  },
  "19": {
    composition: "92% Polyester, 8% Elasthan",
    width: "145 cm",
    weight: "260 g/m²",
    careInstructions: ["Maschinenwäsche 30°C", "Nicht bleichen", "Nicht bügeln", "Nicht im Trockner trocknen"],
    description: "Elastik-Samt mit samtweicher Oberfläche und hohem Stretch. Perfekt für Abendmode und festliche Anlässe.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "20": {
    composition: "55% Baumwolle, 45% Polyester",
    width: "140 cm",
    weight: "180 g/m²",
    careInstructions: ["Maschinenwäsche 30°C", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Italienischer Stickstoff mit feiner Stickerei. Ideal für besondere Blusen und Kleider.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "21": {
    composition: "100% Leinen",
    width: "160 cm",
    weight: "190 g/m²",
    careInstructions: ["Maschinenwäsche 40°C", "Nicht bleichen", "Bügeln Stufe 3", "Nicht im Trockner trocknen"],
    description: "Premium-Leinen in besonders breiter Ausführung. Natürlicher Look und herrlich kühler Tragekomfort.",
    sampleAvailable: true,
    samplePrice: 2.00,
  },
  "22": {
    composition: "85% Schurwolle, 15% Polyamid",
    width: "150 cm",
    weight: "320 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Schurwolle Flanell in warmem Braunton. Zeitloser Stoff für elegante Herbst- und Wintergarderobe.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "23": {
    composition: "90% Schurwolle, 10% Polyamid",
    width: "150 cm",
    weight: "330 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2", "Nicht im Trockner trocknen"],
    description: "Dunkler Flanell in Premium-Qualität. Perfekt für formelle Anzüge und Business-Kleidung.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "24": {
    composition: "100% Merinowolle",
    width: "150 cm",
    weight: "350 g/m²",
    careInstructions: ["Nur chemische Reinigung", "Nicht bleichen", "Bügeln Stufe 2 mit Tuch", "Nicht im Trockner trocknen"],
    description: "Premium Schurwolle Flanell in exquisiter Qualität. Extra fein gewebt für ein luxuriöses Tragegefühl.",
    sampleAvailable: true,
    samplePrice: 3.50,
  },
  "25": {
    composition: "60% Baumwolle, 30% Polyester, 10% Polyacryl",
    width: "140 cm",
    weight: "460 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen"],
    description: "Designer-Bouclé mit angenehm weichem Griff in Blau/Weiß. Perfekt für Blazer und Kostüme.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "26": {
    composition: "96% Viskose, 4% Elasthan",
    width: "140 cm",
    weight: "310 g/m²",
    careInstructions: ["Maschinenwäsche 40°C Feinwäsche", "Nicht bleichen", "Bügeln Stufe 2"],
    description: "Exklusiver Designer-Jersey mit Animaldruck und angenehm warmem Griff. Collection Fall 2026. Couture-Qualität.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "27": {
    composition: "96% Viskose, 4% Elasthan",
    width: "140 cm",
    weight: "310 g/m²",
    careInstructions: ["Maschinenwäsche 40°C Feinwäsche", "Nicht bleichen", "Bügeln Stufe 2"],
    description: "Italienischer Jersey in Haute-Couture-Qualität. Zart weicher Griff, ideal für alle Jersey-Modelle.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "28": {
    composition: "100% Baumwolle",
    width: "150 cm",
    weight: "415 g/m²",
    careInstructions: ["Maschinenwäsche 30°C", "Nicht bleichen", "Bügeln Stufe 3"],
    description: "Designer-Baumwollstoff in Schwarz/Gelb. Mittelschwer, ideal für Kleider, Röcke, Hosen, Jäckchen und Mäntel.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "29": {
    composition: "100% Viskose",
    width: "150 cm",
    weight: "200 g/m²",
    careInstructions: ["Maschinenwäsche 30°C Feinwäsche vorwaschen", "Nicht bleichen", "Bügeln Stufe 1"],
    description: "Hochwertige Jacquard-Viskose aus Italien. Fließend mit weichem Griff in Türkis/Grau/Braun. Ideal für Blusen, Kleider und Röcke.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "30": {
    composition: "55% Viskose, 45% Leinen",
    width: "150 cm",
    weight: "280 g/m²",
    careInstructions: ["Maschinenwäsche 30°C Feinwäsche vorwaschen", "Nicht bleichen", "Bügeln Stufe 2"],
    description: "Italienischer Viskose-Leinen-Stoff mit Blumendruck. Fließender Griff, ideal für Blusen, Kleider, Röcke und weite Hosen.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "31": {
    composition: "50% Polyester, 30% Viskose, 20% Wolle",
    width: "150 cm",
    weight: "660 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen"],
    description: "Italienischer Bouclé-Strickstoff in Hellblau. Schwere Qualität, ideal für Übergangsmäntel, Jacken und elegante Kostüme.",
    sampleAvailable: true,
    samplePrice: 3.00,
  },
  "32": {
    composition: "100% Baumwolle",
    width: "150 cm",
    weight: "730 g/m²",
    careInstructions: ["Maschinenwäsche 40°C vorwaschen", "Nicht bleichen", "Bügeln Stufe 3"],
    description: "Designer-Jacquard-Jeansstoff. Ausgefallen und ausdrucksstark in Blau. Für Jacken, Mäntel und Röcke geeignet.",
    sampleAvailable: true,
    samplePrice: 2.50,
  },
  "33": {
    composition: "60% Seide, 20% Viskose, 20% Polyamid",
    width: "140 cm",
    weight: "180 g/m²",
    careInstructions: ["Chemische Reinigung", "Nicht bleichen", "Nicht bügeln"],
    description: "Eleganter Designer-Seiden-Spitzenstoff mit aufgenähten Seidenstreifen mit Animaldruck. Kann längs oder quer verarbeitet werden.",
    sampleAvailable: true,
    samplePrice: 3.00,
  },
  "34": {
    composition: "100% Baumwolle",
    width: "150 cm",
    weight: "160 g/m²",
    careInstructions: ["Maschinenwäsche 30°C vorwaschen", "Nicht bleichen", "Bügeln Stufe 2"],
    description: "Italienische Baumwolle mit leichtem Griff und Fantasia-Druck in Royal/Grau/Schwarz. Ideal für Blusen und Kleider.",
    sampleAvailable: true,
    samplePrice: 1.50,
  },
};

export const products: Product[] = [
  // --- Page 1: Original products ---
  {
    id: "1",
    name: "Schurwolle Flanell Meterware",
    price: 79.90,
    image: productFlanellBlau,
    category: "Flanell",
    badge: "Bestseller",
    rating: 4.9,
    reviews: 42,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe", "Elegante-Stoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "2",
    name: "Italienischer Flanell Stoff",
    price: 79.90,
    image: productFlanellItal,
    category: "Flanell",
    rating: 4.8,
    reviews: 31,
    fabricTypes: ["Italienische Stoffe", "Italienische Schurwolle", "Designerstoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "3",
    name: "Italienische Schurwolle Flanell",
    price: 79.90,
    image: productSchurwolle,
    category: "Schurwolle",
    rating: 4.7,
    reviews: 28,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe", "Cashmere", "Elegante-Stoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "4",
    name: "Schurwolle Flanell Grau",
    price: 79.90,
    image: productFlanellGrau,
    category: "Flanell",
    rating: 4.8,
    reviews: 35,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe", "Elegante-Stoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "5",
    name: "Premium Schurwolle Flanell",
    price: 99.90,
    image: productFlanellPremium,
    category: "Schurwolle",
    badge: "Premium",
    rating: 4.9,
    reviews: 19,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe", "Cashmere", "Designerstoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "6",
    name: "Pailletten Walkstoff",
    price: 59.90,
    originalPrice: 79.90,
    image: productPailletten,
    category: "Angebot",
    badge: "Angebot",
    rating: 4.6,
    reviews: 24,
    fabricTypes: ["Pailletten & Perlen", "Walkstoffe", "Designerstoffe", "Angebote"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "7",
    name: "Italienischer Flanell Stretch",
    price: 79.90,
    image: productFlanellStretch,
    category: "Flanell",
    badge: "Neu",
    rating: 4.7,
    reviews: 17,
    fabricTypes: ["Stretchstoffe", "Italienische Schurwolle", "Italienische Stoffe"],
    width: "1,55 Meter breit",
    inStock: true,
  },
  {
    id: "8",
    name: "Designer Mantelstoff Meterware",
    price: 69.90,
    originalPrice: 89.90,
    image: productMantelstoff,
    category: "Angebot",
    badge: "Angebot",
    rating: 4.8,
    reviews: 38,
    fabricTypes: ["Mantel & Jackenstoffe", "Designerstoffe", "Elegante-Stoffe", "Angebote"],
    width: "1,50 Meter breit",
    inStock: true,
  },

  // --- Page 2: New products from Weber ---
  {
    id: "9",
    name: "Ital. Schurwolle Blau",
    price: 38.90,
    image: productSchurwolleBlau,
    category: "Schurwolle",
    rating: 4.5,
    reviews: 15,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "10",
    name: "Designer Walkstoff Meterware",
    price: 69.90,
    originalPrice: 79.90,
    image: productWalkstoffDesigner,
    category: "Angebot",
    badge: "Angebot",
    rating: 4.7,
    reviews: 22,
    fabricTypes: ["Walkstoffe", "Designerstoffe", "Angebote"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "11",
    name: "Walkloden",
    price: 59.90,
    image: productWalkloden,
    category: "Walkstoffe",
    rating: 4.6,
    reviews: 20,
    fabricTypes: ["Walkstoffe", "Elegante-Stoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "12",
    name: "Ital. Feinstrickstoff",
    price: 50.90,
    image: productFeinstrick1,
    category: "Strickstoffe",
    rating: 4.5,
    reviews: 12,
    fabricTypes: ["Strickstoffe", "Italienische Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "13",
    name: "Ital. Feinstrickstoff Dunkel",
    price: 50.90,
    image: productFeinstrick2,
    category: "Strickstoffe",
    rating: 4.4,
    reviews: 9,
    fabricTypes: ["Strickstoffe", "Italienische Stoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "14",
    name: "Designer Mantel Stoff",
    price: 99.90,
    image: productMantelDesigner,
    category: "Mantel & Jackenstoffe",
    badge: "Premium",
    rating: 4.9,
    reviews: 27,
    fabricTypes: ["Mantel & Jackenstoffe", "Designerstoffe", "Elegante-Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "15",
    name: "Designer Jacken- & Mantelstoff",
    price: 94.90,
    image: productJackenMantel,
    category: "Mantel & Jackenstoffe",
    rating: 4.8,
    reviews: 14,
    fabricTypes: ["Mantel & Jackenstoffe", "Designerstoffe", "Elegante-Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "16",
    name: "Westfalenstoff",
    price: 22.99,
    image: productWestfalenstoff,
    category: "Baumwollstoffe",
    rating: 4.3,
    reviews: 33,
    fabricTypes: ["Westfalenstoffe", "Baumwollstoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "17",
    name: "Designer Leinen Meterware",
    price: 59.90,
    image: productLeinenDesigner,
    category: "Leinen",
    rating: 4.6,
    reviews: 18,
    fabricTypes: ["Italienisches Leinen", "Designerstoffe", "Italienische Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "18",
    name: "Italienische Schurwolle",
    price: 79.90,
    image: productSchurwolleItal,
    category: "Schurwolle",
    rating: 4.7,
    reviews: 21,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe", "Elegante-Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "19",
    name: "Elastik-Samt",
    price: 49.90,
    image: productElastikSamt,
    category: "Designer",
    rating: 4.5,
    reviews: 16,
    fabricTypes: ["Stretchstoffe", "Elegante-Stoffe", "Kleider & Blusenstoffe"],
    width: "1,45 Meter breit",
    inStock: true,
  },
  {
    id: "20",
    name: "Italienischer Stickstoff",
    price: 49.90,
    image: productStickstoff,
    category: "Designer",
    rating: 4.4,
    reviews: 11,
    fabricTypes: ["Stickereistoffe", "Italienische Stoffe", "Kleider & Blusenstoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "21",
    name: "Designer Leinen",
    price: 49.90,
    image: productLeinen,
    category: "Leinen",
    rating: 4.6,
    reviews: 25,
    fabricTypes: ["Italienisches Leinen", "Designerstoffe", "Italienische Stoffe"],
    width: "1,60 Meter breit",
    inStock: true,
  },
  {
    id: "22",
    name: "Schurwolle Flanell Braun",
    price: 79.90,
    image: productFlanellBraun,
    category: "Flanell",
    rating: 4.7,
    reviews: 19,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe", "Elegante-Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "23",
    name: "Schurwolle Flanell Dunkel",
    price: 79.90,
    image: productFlanellDunkel,
    category: "Flanell",
    rating: 4.8,
    reviews: 23,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe", "Elegante-Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "24",
    name: "Premium Schurwolle Flanell",
    price: 99.90,
    image: productFlanellPremium2,
    category: "Schurwolle",
    badge: "Premium",
    rating: 4.9,
    reviews: 31,
    fabricTypes: ["Italienische Schurwolle", "Italienische Stoffe", "Cashmere", "Designerstoffe", "Elegante-Stoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },

  // --- Page 3: Homepage featured products ---
  {
    id: "25",
    name: "Designer Bouclé",
    price: 91.90,
    image: productBoucleDesigner,
    category: "Bouclé",
    rating: 4.8,
    reviews: 14,
    fabricTypes: ["Bouclé & Tweed", "Designerstoffe", "Baumwollstoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "26",
    name: "Designer Jersey Animaldruck",
    price: 45.90,
    image: productJerseyDesigner,
    category: "Jersey",
    badge: "Neu",
    rating: 4.6,
    reviews: 8,
    fabricTypes: ["Italienischer Jersey", "Designerstoffe", "Stretchstoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "27",
    name: "Italienischer Jersey",
    price: 44.90,
    image: productJerseyItal,
    category: "Jersey",
    badge: "Neu",
    rating: 4.7,
    reviews: 12,
    fabricTypes: ["Italienischer Jersey", "Italienische Stoffe", "Stretchstoffe"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "28",
    name: "Designer Baumwollstoff",
    price: 49.90,
    image: productBaumwolleDesigner,
    category: "Baumwollstoffe",
    rating: 4.5,
    reviews: 16,
    fabricTypes: ["Baumwollstoffe", "Designerstoffe", "Kleider & Blusenstoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "29",
    name: "Italienische Jacquard-Viskose",
    price: 44.90,
    image: productViskoseItal,
    category: "Viskose",
    badge: "Neu",
    rating: 4.5,
    reviews: 7,
    fabricTypes: ["Italienische Stoffe", "Jacquard-Stoffe", "Kleider & Blusenstoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "30",
    name: "Ital. Viskose-Leinen Blumendruck",
    price: 29.90,
    image: productLeinenViskose,
    category: "Leinen",
    badge: "Neu",
    rating: 4.6,
    reviews: 10,
    fabricTypes: ["Italienisches Leinen", "Italienische Stoffe", "Kleider & Blusenstoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "31",
    name: "Italienischer Bouclé-Strickstoff",
    price: 44.90,
    originalPrice: 59.90,
    image: productBoucleItal,
    category: "Bouclé",
    badge: "Angebot",
    rating: 4.7,
    reviews: 19,
    fabricTypes: ["Bouclé & Tweed", "Strickstoffe", "Mantel & Jackenstoffe", "Angebote"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "32",
    name: "Designer Jacquard-Jeansstoff",
    price: 49.90,
    image: productJeansstoffDesigner,
    category: "Baumwollstoffe",
    badge: "Neu",
    rating: 4.4,
    reviews: 6,
    fabricTypes: ["Baumwollstoffe", "Designerstoffe", "Mantel & Jackenstoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
  {
    id: "33",
    name: "Designer Seiden-Spitzenstoff",
    price: 62.90,
    originalPrice: 79.90,
    image: productSpitzeDesigner,
    category: "Spitzenstoffe",
    badge: "Angebot",
    rating: 4.8,
    reviews: 11,
    fabricTypes: ["Spitzenstoffe", "Italienische Seide", "Designerstoffe", "Angebote"],
    width: "1,40 Meter breit",
    inStock: true,
  },
  {
    id: "34",
    name: "Italienische Baumwolle Fantasia",
    price: 23.90,
    image: productBaumwolleItal,
    category: "Baumwollstoffe",
    badge: "Neu",
    rating: 4.3,
    reviews: 9,
    fabricTypes: ["Baumwollstoffe", "Italienische Stoffe", "Kleider & Blusenstoffe"],
    width: "1,50 Meter breit",
    inStock: true,
  },
];